---
services: docker

env:
  # tests/test.yml
  - distro: centos7
    playbook: test.yml
    prefix: ''
    http_port: 8080
  - distro: fedora24
    site: test.yml
    prefix: ''
    http_port: 8080
  - distro: ubuntu1604
    playbook: test.yml
    prefix: ''
    http_port: 8080
  - distro: ubuntu1404
    playbook: test.yml
    prefix: ''
    http_port: 8080
  - distro: debian8
    playbook: test.yml
    prefix: ''
    http_port: 8080


  # tests/test-jobs.yml
  - distro: centos7
    playbook: test-jobs.yml
    prefix: ''
    http_port: 8080
  - distro: fedora24
    site: test-jobs.yml
    prefix: ''
    http_port: 8080
  - distro: ubuntu1604
    playbook: test-jobs.yml
    prefix: ''
    http_port: 8080
  - distro: ubuntu1404
    playbook: test-jobs.yml
    prefix: ''
    http_port: 8080
  - distro: debian8
    playbook: test-jobs.yml
    prefix: ''
    http_port: 8080


script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Make sure Jenkins is running.
  - 'docker exec --tty ${container_id} env TERM=xterm curl http://localhost:$http_port/$prefix'

after_failure:
  # Check what happened on systemd systems.
  - 'docker exec --tty ${container_id} env TERM=xterm systemctl -l status jenkins.service'
  - 'docker exec --tty ${container_id} env TERM=xterm journalctl -xe --no-pager'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
